name: ease_split
description: A Flutter to split bills and expenses among friends

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.1.0
  dartz: ^0.10.1
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  google_sign_in: ^5.4.1
  uuid: ^3.0.6
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  auto_route: ^5.0.1
  font_awesome_flutter: ^10.1.0
  json_annotation: ^4.6.0
  cloud_firestore: ^3.4.6
  cloud_firestore_odm: ^1.0.0-dev.28
  rxdart: ^0.27.5
  shimmer: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  auto_route_generator: ^5.0.1
  json_serializable: ^6.3.1
  cloud_firestore_odm_generator: ^1.0.0-dev.28

flutter:

  uses-material-design: true

  assets:
    - assets/

