// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHjyJ3EJ3jmMxLuEcm1315kiuZmlYKTk',
    appId: '1:981587668248:web:b8595932fe00a905a7c26d',
    messagingSenderId: '981587668248',
    projectId: 'ease-split',
    authDomain: 'ease-split.firebaseapp.com',
    storageBucket: 'ease-split.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdrQNJsPVMZ0WaOyHBpEmf4DA66hV4g9Q',
    appId: '1:981587668248:android:317102b54f4ecc5aa7c26d',
    messagingSenderId: '981587668248',
    projectId: 'ease-split',
    storageBucket: 'ease-split.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1l11vZn104D0ckxWpwa9qAUXdFhHIsNA',
    appId: '1:981587668248:ios:e2d9772eb371ac87a7c26d',
    messagingSenderId: '981587668248',
    projectId: 'ease-split',
    storageBucket: 'ease-split.appspot.com',
    iosClientId: '981587668248-o523rgv9uoe66lro4i2eqa3ajer670ln.apps.googleusercontent.com',
    iosBundleId: 'io.github.amansikarwar.easeSplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1l11vZn104D0ckxWpwa9qAUXdFhHIsNA',
    appId: '1:981587668248:ios:e2d9772eb371ac87a7c26d',
    messagingSenderId: '981587668248',
    projectId: 'ease-split',
    storageBucket: 'ease-split.appspot.com',
    iosClientId: '981587668248-o523rgv9uoe66lro4i2eqa3ajer670ln.apps.googleusercontent.com',
    iosBundleId: 'io.github.amansikarwar.easeSplit',
  );
}
